### ISSUE TITLE
[Maintenance] The gpt2-en link doesn't work

### ISSUE THREAD

**Issue by LinZichuan** [boliangz/dstc9#1]
Hi, thanks for you code!

When I try to download gpt2-en model, I cannot access to the link http://10.186.1.122:8080/~luban/gpt2_en/.

Is there any other way to download the pretrained model?

Thanks!

**Comment by boliangz** [comment]
Please use the following command to download gpt2_en model:
```
mkdir gpt2_en
wget -P gpt2_en/ https://storage.googleapis.com/dstc9_submission/gpt2_en/config.json
wget -P gpt2_en/ https://storage.googleapis.com/dstc9_submission/gpt2_en/merges.txt
wget -P gpt2_en/ https://storage.googleapis.com/dstc9_submission/gpt2_en/pytorch_model.bin
wget -P gpt2_en/ https://storage.googleapis.com/dstc9_submission/gpt2_en/vocab.json
```

`end2end/soloist/README.md` is also updated with this information.
