### ISSUE TITLE
[BUG] Human evaluation process.

### ISSUE THREAD

**Issue by mianzhang** [boliangz/dstc9#2]
Hi,

During the process of human evaluation (python end2end/human_eval_example.py), I encounter a problem about "position_ids" and whatever I said to the agent, I got the same feedback: "i'm really sorry but i couldn't understand what you just said. could you please provide more specific information ? Or please type "restart" to restart the conversation." Details are as follows:
![image](https://user-images.githubusercontent.com/31158330/111055180-313a1c80-84ae-11eb-84ad-5602ed46da6f.png)
![image](https://user-images.githubusercontent.com/31158330/111055188-4747dd00-84ae-11eb-95e1-3d2d92cdd2de.png)
![image](https://user-images.githubusercontent.com/31158330/111055192-5af34380-84ae-11eb-957b-dd7742566180.png)
What are the possible reasons?

Best,
Mian

**Comment by boliangz** [comment]
can you check the version of your transformer module by:
```
import transformers
print(transformers.__version__)
```

if the version is not 2.9.0, try to install transformers 2.9.0:
```
pip uninstall transformers
pip install transformers==2.9.0
```

**Comment by mianzhang** [comment]
It works, thanks a lot.
